# Generated by Django 4.1.3 on 2023-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='cap',
            field=models.CharField(default=-2013, max_length=5),
            preserve_default=False,
        ),
    ]
