# Generated by Django 4.1.3 on 2023-08-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_about_us_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
                ('cpassword', models.IntegerField()),
            ],
        ),
    ]
