# Generated by Django 4.1.3 on 2023-08-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_user',
            name='address',
            field=models.TextField(default=-2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_user',
            name='gender',
            field=models.CharField(default=-2018, max_length=20),
            preserve_default=False,
        ),
    ]
