# Generated by Django 4.1.3 on 2023-08-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_add_user_address_add_user_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_user',
        ),
    ]
