# Generated by Django 4.1.3 on 2023-08-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_add_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_user',
        ),
    ]
