# Generated by Django 4.1.3 on 2023-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0008_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_user',
            name='image',
            field=models.CharField(default=0.00024715768660405336, max_length=500),
            preserve_default=False,
        ),
    ]
