# Generated by Django 4.1.3 on 2023-08-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0009_add_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_user',
            new_name='register',
        ),
    ]
