# Generated by Django 4.1.3 on 2023-08-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0010_rename_add_user_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='tbl_register',
        ),
    ]
