# Generated by Django 4.1.3 on 2023-09-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0011_rename_register_tbl_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_register',
            name='cpassword',
        ),
        migrations.RemoveField(
            model_name='tbl_register',
            name='password',
        ),
    ]
