# Generated by Django 4.1.3 on 2023-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0012_remove_tbl_register_cpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=10)),
            ],
        ),
    ]
