# Generated by Django 4.1.3 on 2023-09-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0013_tbl_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('designation', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('mob', models.IntegerField()),
            ],
        ),
    ]
