# Generated by Django 4.1.3 on 2023-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0015_tbl_appoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_appoinment',
            name='symtoms',
            field=models.TextField(default=-2015),
            preserve_default=False,
        ),
    ]
