# Generated by Django 4.1.3 on 2023-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0016_tbl_appoinment_symtoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('fee', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='tbl_appoinment',
            name='fee',
            field=models.IntegerField(default=0.0011863568956994562),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_appoinment',
            name='photo',
            field=models.ImageField(default=-2015, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
