# Generated by Django 4.1.3 on 2023-09-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0017_doctor_availability_tbl_appoinment_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_availability',
            name='date',
        ),
        migrations.AddField(
            model_name='doctor_availability',
            name='day',
            field=models.TextField(default=-2022),
            preserve_default=False,
        ),
    ]
