# Generated by Django 4.1.3 on 2023-10-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0018_remove_doctor_availability_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_availability',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='doctor_availability',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
