# Generated by Django 4.1.3 on 2023-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0019_rename_doctor_name_doctor_availability_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_appoinment',
            name='status',
            field=models.CharField(default=-1014, max_length=20),
            preserve_default=False,
        ),
    ]
