# Generated by Django 4.1.3 on 2023-10-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0020_tbl_appoinment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_appoinment',
            name='booking_type',
            field=models.CharField(default=-2013, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_appoinment',
            name='id_proof',
            field=models.CharField(default=0.002965892239248641, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_appoinment',
            name='image1',
            field=models.CharField(default=-2021, max_length=500),
            preserve_default=False,
        ),
    ]
