# Generated by Django 4.1.3 on 2023-10-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0021_tbl_appoinment_booking_type_tbl_appoinment_id_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_availability',
            name='specialization',
            field=models.CharField(default=-2033, max_length=30),
            preserve_default=False,
        ),
    ]
