# Generated by Django 4.1.3 on 2023-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0022_doctor_availability_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_appoinment',
            name='username',
            field=models.CharField(default=-2020, max_length=30),
            preserve_default=False,
        ),
    ]
