# Generated by Django 4.1.3 on 2023-10-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0024_alter_tbl_appoinment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='symtoms',
            field=models.TextField(default=None),
        ),
    ]
