# Generated by Django 4.0.4 on 2023-10-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0026_alter_tbl_appoinment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
