# Generated by Django 4.0.4 on 2023-10-13 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0027_alter_tbl_appoinment_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='address',
            field=models.TextField(default='data'),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 13, 10, 43, 17, 277253)),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='fee',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='mob',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='status',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='symtoms',
            field=models.TextField(default='text'),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 13, 10, 43, 17, 277253)),
        ),
    ]
