# Generated by Django 4.0.4 on 2023-10-19 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0028_alter_tbl_appoinment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 10, 29, 29, 235127)),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='mob',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 19, 10, 29, 29, 235127)),
        ),
    ]
