# Generated by Django 4.0.4 on 2023-10-19 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0029_alter_tbl_appoinment_date_alter_tbl_appoinment_mob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 10, 53, 15, 303035)),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='doctor',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 19, 10, 53, 15, 303035)),
        ),
    ]
