# Generated by Django 4.0.4 on 2023-10-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0030_alter_tbl_appoinment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='date',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='tbl_appoinment',
            name='time',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
